[profile.default]
optimizer = true
optimizer_runs = 50
via_ir = true
bytecode_hash = "ipfs"
auto_broadcast = true
remappings = [
    "forge-std=lib/forge-std/src/",
    "openzeppelin=lib/openzeppelin-contracts/",
    "solmate=lib/solmate/src/",
    "ds-test=lib/forge-std/lib/ds-test/src/",
    "party-addresses=lib/party-addresses/",
    "uniswap-v2-core=lib/v2-core/contracts/",
    "uniswap-v2-periphery=lib/v2-periphery/contracts/",
    "erc20-creator=lib/erc20-creator/src/",
    "@openzeppelin/contracts=lib/erc20-creator/lib/openzeppelin-contracts/contracts/",
    "erc4626-tests=lib/openzeppelin-contracts/lib/erc4626-tests/",
    "openzeppelin-contracts=lib/openzeppelin-contracts/",
    "party-protocol=lib/erc20-creator/lib/party-protocol/",
    "v2-core=lib/v2-core/contracts/",
    "v2-periphery=lib/v2-periphery/contracts/"
]
